### ISSUE TITLE
Pot doesn't output correctly

### ISSUE THREAD

**Issue by ideascape** [Hansigzandrinovka/BlackJack368Project#1]
I think it is because the addRefresh calls make use of the copy function, which returns an object. This is necessary, because if we pass this.pot without copying it somehow, when the refreshQueue finally outputs the refresh, it prints the current state of the object, instead of the the state it had when addRefresh was first called. So we need to figure out some other way of storing the state of the pot.

When a working method is found, all of the addRefresh calls will need to be updated.

**Comment by agbassist** [comment]
Mostly fixed, shows NaN at somepoint, we'll have to figure that out. My guess is the refresh Object is not  created correctly at some point in the code

**Comment by agbassist** [comment]
Works. No more NaN.
