### ISSUE TITLE
Fix distributeWinnings game logic function

### ISSUE THREAD

**Issue by ideascape** [Hansigzandrinovka/BlackJack368Project#10]
This function is supposed to take an array of winning players as input, and split the pot between them (e.g., if there were two winners, half of the pot should be added to the first player and the other half to the second player's bankroll). Feel free to totally restructure this, it doesn't work.

**Comment by agbassist** [comment]
I figured out how to fix this. If you guys don't like my solution, feel free to redo it, but I basically cross-checked the names of winners and players, and if they were the same, distributed the earnings.
