### ISSUE TITLE
Add message listing the names of the players who won at the end of the round, and the amount they won

### ISSUE THREAD

**Issue by ideascape** [Hansigzandrinovka/BlackJack368Project#16]
Right now it's a bit hard to see who won the round.

**Comment by mbechtel2** [comment]
Just changed the resolveGame method to show the winner and the size of the pot at the end of the round. I don't have it split the pot if there is more than one winner but it will still show the names of all of the winners.

**Comment by ideascape** [comment]
Amount didn't report quite right (it included the players bet). I also added support for outputting multiple winners and their exact winnings.

I should be studying for my physics final. I blame Hans.
