### ISSUE TITLE
regarding your 'fix bug in AI handling' commit + update other addRefresh calls

### ISSUE THREAD

**Issue by ideascape** [Hansigzandrinovka/BlackJack368Project#17]
I made a comment (copied below) but I wasn't sure if you got it. Just opening a new issue to be sure.

---

Don't disable the refresh. There was a bug, but it should still addRefresh but look like this:

addRefresh({
playerArray:copy(this.players),
pot:0+(this.pot),
console_message:'',
showCards:true,
buttonsToShow:"play"
});

Everywhere in the code, playerArray should be a copy, and pot should be 0 + pot. I was going to make a commit fixing this stuff, but I want to avoid a merge conflict so you should probably do it. There are other places with this issue as well: do a search for 'pot:' and a search for 'playerArray:' and you should be able to find the places this needs to be fixed.

**Comment by mbechtel2** [comment]
Yea, turns out not having the copy in the addRefresh I commented out was the problem. I believe I fixed all of the addRefresh's that didn't have copy or 0+this.pot but let me know if I missed any.

**Comment by ideascape** [comment]
Cool, thanks Michael
