### ISSUE TITLE
Place bet defaults to 100 on display

### ISSUE THREAD

**Issue by Hansigzandrinovka** [Hansigzandrinovka/BlackJack368Project#18]
This could be a fault player-end, but I'll look into it. Let me know if anyone else has the same issue. I pulled commit 054dca8 and opened Blackjack.html. When it asked me to bet, I would put in 2 or 900, and the value would go from 10000 to 9900.

**Comment by ideascape** [comment]
This is a known issue, so this is a dupe I think. See issue #2 and #4.
