### ISSUE TITLE
in game logic getBets function, enable support for player setBet() and test  that it works

### ISSUE THREAD

**Issue by ideascape** [Hansigzandrinovka/BlackJack368Project#2]
Notes on requirements for setBet()

create setBet() function. takes bet amount as input, or null (if we are setting bet for AI). result is:
  if the player is an AI, poll the AI bet function for a bet amount
  if player is human, use amount given
  set bet attribute to the amount returned
  update player bankroll
  set betPlaced to true
  if player attempts to bet more than he has in his bankroll, bet amount is everything that remains. if bankroll is empty, bet amount should be zero. Function should never exit unsuccessfully

**Comment by Hansigzandrinovka** [comment]
setBet works as I expect it:
test code is as follows: Note that AIs bet 100 (as expected for AI), whereas players bet the amount written (expect 55)
//-----------------Test Code---------------------
var theDeck = new Deck();
theDeck.initDeck();
var derfPlayer = new Player("Sam","Pro",400,theDeck);
var cardUno = theDeck.drawCards(3);
for(var x = 0; x < cardUno.length; x++)
{
    Output("Card draw " + cardUno[x].suit + " " + cardUno[x].value);
}
derfPlayer.givePlayerCards(cardUno);
Output("Player value " + derfPlayer.getTotalAmount());
derfPlayer.setBet(55);
Output("Player bet " + derfPlayer.getBet());

//--------END TEST CODE---------

Thus it is time to incorporate setBet method into operations.

**Comment by ideascape** [comment]
Sweet. I think already have a call to setBet in both getBets and getPlayerBet. They just need to be commented out and dummy code removed.

**Comment by ideascape** [comment]
Er I mean right now they are commented out and they just need to be enabled.

**Comment by agbassist** [comment]
I think I uncommented the right things. Betting works now.
