### ISSUE TITLE
No incentive to Bet

### ISSUE THREAD

**Issue by agbassist** [Hansigzandrinovka/BlackJack368Project#23]
I just realized that our game is a little flawed in that there is no incentive to bet more than the minimum, because you can only lose more money by betting more. I can live with that for our submission, but if it would not be too difficult and if we found enough time, we could make the betting round repeat until everyone had called or folded the highest bet.

My guess is we probably just won't worry about it though.

**Comment by Hansigzandrinovka** [comment]
Potential fix: you get double your payout if you win. Or alternatively, reduce the return from others for winning by the percentage yours was of theirs:
IE you bet 1% of the highest, so you get 2% of everyone's payout.

**Comment by ideascape** [comment]
Alex: Yeah, this is a problem. I like the idea of poker-style raises, calls and folds. It would change the character of the game entirely and make it a lot more interesting, I think. I'm not sure how it works in poker, but we could limit it to one raise per player per turn to keep the betting from taking too long.

This would be a bit involved to implement, though. We would need call, fold, and raise buttons, which wouldn't be hard, but there would have to be a significant change in how the betting logic works. Not sure how hard that would be, I'll have to think about it a bit.

Hans: The first one you mention is an interesting idea, but aside from the implications of creating some kind of central bank that gives out extra money, I wonder if this would create the opposite incentive. I.e., betting as much as you can. I'm not sure I understand how the second idea would work; it might help to give an example with numbers.
