### ISSUE TITLE
Add backend support for second call/fold round during betting

### ISSUE THREAD

**Issue by ideascape** [Hansigzandrinovka/BlackJack368Project#26]
Alex had an idea which is that the players will enter their bets during the first round, but the bets will be hidden. Then during the second round, all players will be required to either call or fold in response to the maximum bet that was entered in the first round. This should at least partially solve the betting problem and make the game a little more fun.

With this system I think we should have a maximum as well as a minimum bet. Crazy high bets could negatively impact the game.

**Comment by Hansigzandrinovka** [comment]
This is an interesting idea, but it poses the issue of the max bid being over what someone else has. Say "bob" has 200, and "shem" bets 500. The question is this: does the max bid lower to the amount the lowest player can bid, or does the chump only bid what he has? The second one is easier to implement imo.

If a player "holds," does that mean they drop out of the round? In that case, they could just become busted when they hold.

**Comment by ideascape** [comment]
The way I ended up implementing it was to force the player to fold if he doesn't have enough to match. That's actually kind of unfair, I think your idea of just allowing the player to bid what he has might be better. And yeah, folding means they don't play the rest of the round.

**Comment by ideascape** [comment]
Stuff pretty much works now.
