### ISSUE TITLE
Sometimes, during a human player's turn, the game doesn't let you hit when it should

### ISSUE THREAD

**Issue by ideascape** [Hansigzandrinovka/BlackJack368Project#3]
E.g., two aces and a queen gets marked as busted. Function to look at is makeMove in game logic. Possibly the problem may be with getTotalAmount() player function, which should calculate the total such that it is as close to 21 as possible without going over (aces being evaluated in the most favorable way possible).

**Comment by Hansigzandrinovka** [comment]
It is possible this issue stems from the makeMove method. It appears that rsolveGame() is called after each player makes one move, meaning that you can only draw a card or pass before your turn is over.
It may be better to have a detection var to see if every player is finished.
IE: make it true initially, then when detects a player is not finished (just drew a card and not over limit) then prevents resolveGame from running.

**Comment by ideascape** [comment]
Yeah, actually resolveGame is not supposed to be called there, I thought that had been removed. Fixed
