### ISSUE TITLE
It does not let people call or fold after the first round

### ISSUE THREAD

**Issue by agbassist** [Hansigzandrinovka/BlackJack368Project#30]

**Comment by ideascape** [comment]
Yeah, I noticed this. I think resetGame probably needs to be modified. And probably the player reset function.

**Comment by agbassist** [comment]
Yeah it looks like it tries to revert back to the old game logic after the first round.

**Comment by ideascape** [comment]
I just pushed a fix.

**Comment by agbassist** [comment]
Sweet! It's working great!

**Comment by ideascape** [comment]
🎱 
:)
