### ISSUE TITLE
Issues in long-term game

### ISSUE THREAD

**Issue by agbassist** [Hansigzandrinovka/BlackJack368Project#34]
It seems like after you play a certain amount of time, the deck runs out of cards or something. We might have to check over how the deck is reset at the end of a round.

**Comment by ideascape** [comment]
Hmm... we'll have to test and see if the automatic reshuffle is getting triggered when the deck gets low.

**Comment by ideascape** [comment]
Card shuffle wasn't working. Fixed. Test code below for reference:

var testdeck = new Deck();
testdeck.initDeck();
var count =0;
for(var i = 0; i < 2000; i++)
{
  count++;
  var card = testdeck.drawCards(1);
  testdeck.returnCards(card);
    if(i % 52 == 0){console.log("active length: " + testdeck.active.length.toString() + " discards length: " + testdeck.discards.length.toString() + " total length: " + (testdeck.active.length+testdeck.discards.length).toString() + " cards drawn: " + count.toString())};
}
