### ISSUE TITLE
in resolveGame, enable support for Alex's continue/quit buttons and see if they display correctly

### ISSUE THREAD

**Issue by ideascape** [Hansigzandrinovka/BlackJack368Project#6]
buttonsToShow should be 'continue'

**Comment by mbechtel2** [comment]
The continue button should now start a new turn and play it out, including gathering player bets. I don't know what we want to happen when the user quits so I'll leave this issue open till we can implement that as well.

**Comment by agbassist** [comment]
The quit button just reloads the page. All works.
