### ISSUE TITLE
add support for continue feature/test player reset function

### ISSUE THREAD

**Issue by ideascape** [Hansigzandrinovka/BlackJack368Project#7]
Issue#6 is prerequisite. You will need to add a call to resetGame() in the event listener for the continue button (line 184 at this writing). When user clicks the continue button, the game and player info needs to be reset, but keep player bankrolls intact.

Test that resetGame does what it is supposed to. This will mostly mean testing that the player function reset() does what it is supposed to.

Quit feature will be a separate task.

**Comment by agbassist** [comment]
This seems to work from my testing.
