### ISSUE TITLE
Figure out why players are not getting marked as busted in the interface

### ISSUE THREAD

**Issue by ideascape** [Hansigzandrinovka/BlackJack368Project#8]
The text 'BUSTED' should appear in red next to the player's name. This feature worked when Alex and I were testing it, so there's a good chance it's an issue in the game logic. Are the players getting marked as busted when they should be? When we make an addRefresh call, does it add the correct state of the player? I'm not sure what the problem is.

Might be a good idea to start by testing that the interface feature still works. If we manually set player.busted = true for all players and call addRefresh, does it display all players as busted? If not, there may be an issue with the interface code somewhere.

**Comment by agbassist** [comment]
It wasn't working because I forgot a closing tag in the html. Should be fixed now.
